import './globals.css'
import type { Metadata } from 'next'
import { css } from '../../styled-system/css'
import { montserrat } from '@/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`
        dark
        ${montserrat.variable}
        ${css({
          backgroundColor: 'page.backgroundColor',
          textStyle: 'body',
          color: 'page.textColor'

        })}
      `}>{children}</body>
    </html>
  )
}
